In [2]:
using LinearAlgebra

A Decomposição QR consiste em encontrar duas matrizes $Q$ e $R$ tais que $A = QR$.

Onde:


   $Q$ é uma matriz ortogonal que representa uma base ortonormal para $A$.
   
   
   $R$ é uma matriz triangular superior que representa as coordenadas dos vetores de A na base ortogonal Q.
  

O algoritmo abaixo é uma forma de encontrar essa decomposição baseada no algoritmo de ortogonalização de Gram-Schmidt.

In [3]:
# Recebe uma matriz A como parâmetro
# Retorna duas matrizes Q e R
#
function qrDecomposition(A)
    m, n = size(A) 
    
    Q = zeros(m, n) # vetores de A ortonormalizados
    R = zeros(n, n) # matriz de coordenadas para A na base Q
    
    # primeira iteração
    a1 = A[:,1]
    r11 = norm(a1)
    q1 =  a1 / r11    # normaliza o primeiro vetor
    Q[:,1] = q1       # adiciona o vetor na matriz Q
    R[1,1] = r11      # adiciona a coordenada de 
    
    for i = 2:n
        a = copy(A[:,i])  
        ai = copy(A[:,i])
        
        for j = 1:(i-1)
            qj = copy(Q[:,j])
            rji = ai'*qj
            
            a = a - qj*(rji)
            
            R[j,i] = rji
        end
        
        rii = norm(a)
        q = copy(a) / rii
        
        Q[:,i] = copy(q)
        R[i,i] = rii
    end
    
    return Q, R
end

qrDecomposition (generic function with 1 method)

### Testes:

In [14]:
A = randn(4,4)

4×4 Matrix{Float64}:
 -1.18967    -0.683629   0.836411  -0.000646688
  0.0043093  -0.749437   0.177539   1.17605
 -1.15811     0.204138  -0.724151  -1.76278
  0.289404   -1.01461    0.642031   0.968888

In [15]:
Q, R = qrDecomposition(A)

([-0.7058993909852055 -0.39339934004739274 0.5783535041793421 0.11158061328235964; 0.00255695879760969 -0.5208760763362031 -0.48650607462241663 0.7014224222376961; -0.6871765471111031 0.2211090867044838 -0.6354503986053137 -0.27404736048631967; 0.17172042647537655 -0.7245935716852495 -0.15818297781781454 -0.6484245496063648], [1.6853220946926593 0.16614951798602925 0.017901499624490252 1.3811792361831419; 0.0 1.4396172939523868 -1.0468472078636566 -1.7041346087530742; 0.0 0.0 0.7559716573279959 0.3943677166018832; 0.0 0.0 0.0 0.6796656729913809])

Verificando a igualdade $A = QR$

In [17]:
Q*R

4×4 Matrix{Float64}:
 -1.18967    -0.683629   0.836411  -0.000646688
  0.0043093  -0.749437   0.177539   1.17605
 -1.15811     0.204138  -0.724151  -1.76278
  0.289404   -1.01461    0.642031   0.968888

In [16]:
norm(A - Q*R) <= 1e-15

true

Verificando se Q é ortonormal

In [13]:
Q*Q'

4×4 Matrix{Float64}:
  1.0           7.35388e-17  -4.38525e-16   1.82403e-16
  7.35388e-17   1.0           2.64821e-16  -2.33048e-16
 -4.38525e-16   2.64821e-16   1.0          -1.94122e-17
  1.82403e-16  -2.33048e-16  -1.94122e-17   1.0

In [20]:
norm(I - Q*Q') <= 1e-15

true